---
title: "Gecco Challenge Dataset - Water Quality"
output: html_notebook
---
Data collection for water quality monitoring

Source: https://www.spotseven.de/gecco/gecco-challenge


## Load series
```{r}
library(dalts)
library(daltoolbox)
library(harbinger)
library(tspredit)

## Load series ----------------------
data(gecco)
gecco$gecco
```



```{r}
serie <- gecco$gecco$tp
eventos_rotulados <- gecco$gecco$event
head(serie,5)
```


```{r}
plot(serie, type = "l", main = "Série temporal - tp (GECCO)", xlab = "Tempo", ylab = "tp")

```


```{r}
# Create object ts_data with horizon = 1
ts <- ts_data(serie, sw = 1)

# Separate Training and Test samples
samp <- ts_sample(ts, test_size = 500)

#  Input/output projection
io_train <- ts_projection(samp$train)
io_test <- ts_projection(samp$test)

```

```{r}
# Create ARIMA and train
model <- ts_arima()
model <- fit(model, x = io_train$input, y = io_train$output)
```

```{r}

# Predicting next 500 steps
prediction <- predict(model, x = io_test$input[1,], steps_ahead = 500)

# Converting to vector
pred <- as.vector(prediction)
real <- as.vector(io_test$output)

# Evaluate
ev_test <- evaluate(model, real, pred)
ev_test
```


